SELECT * 
FROM
	CUSTOMER_BEHAVIOR_ANALYSIS
	fetch first 5 rows only;
--- 2.Which category generates highest revenue?
SELECT
	CATEGORY,
	ROUND(SUM(PURCHASE_AMOUNT)::NUMERIC, 2) AS HIGHEST_REVENUE
FROM
	CUSTOMER_BEHAVIOR_ANALYSIS
GROUP BY
	1
	order by 2 desc;

-- ❓ Business Problem :- Company does not know which category contributes most to revenue.


-- 🚀 Impact :- 
			 -- Helps prioritize high-performing categories
			 -- Optimizes inventory planning
			 -- Improves marketing ROI
------------------------------------------------------------------------------------
-- 2. Are discounts actually increasing purchase value?
SELECT * 
FROM
	CUSTOMER_BEHAVIOR_ANALYSIS
	fetch first 5 rows only;

select 
	discount_applied,
	ROUND(SUM(PURCHASE_AMOUNT)::NUMERIC, 2) as total_revenue,
	ROUND(avg(PURCHASE_AMOUNT)::NUMERIC, 2) as avg_purchase
	from CUSTOMER_BEHAVIOR_ANALYSIS
	group by 1;

--❓ Business Problem :- Discounts may reduce profit without increasing sales.

-- 🚀 Impact :- 
				--Identify effectiveness of discounts
				--Reduce unnecessary discount costs
				--Improve profit margins

-------------------------------------------------------------------------------------------
-- 3. What is the total revenue generated by male and female customer?
SELECT * 
FROM
	CUSTOMER_BEHAVIOR_ANALYSIS
	fetch first 5 rows only;
select 
	gender,
	ROUND(SUM(PURCHASE_AMOUNT)::NUMERIC, 2) As highest_revenue
	from CUSTOMER_BEHAVIOR_ANALYSIS
	group by 1
	order by 2 desc;
--❓ Business Problem :- Lack of understanding of revenue contribution by gender segments.

--🚀 Impact:- 
			--Helps design targeted marketing campaigns
			--Improves customer segmentation strategy
			--Enhances personalization efforts

---------------------------------------------------------------------------------------------------
--- 4. Which customer used a discount but still spent more then the average purchase amount

SELECT * 
FROM
	CUSTOMER_BEHAVIOR_ANALYSIS
	fetch first 5 rows only;
	
select customer_id,
purchase_amount,
discount_applied
from CUSTOMER_BEHAVIOR_ANALYSIS 
where discount_applied = 'Yes' 
and purchase_amount >= (select avg(purchase_amount) from CUSTOMER_BEHAVIOR_ANALYSIS)
order by purchase_amount desc
fetch first 5 rows only;
--❓ Business Problem:- Company cannot identify high-spending customers who are also discount users.


--🚀 Impact:- 
			--Identifies premium discount-sensitive customers
			--Enables targeted discount campaigns
			--Improves customer retention and revenue

-----------------------------------------------------------------------------------------------------------------------
--5. Which are the top/bottom 5 products with the highest average review rating. 
SELECT * 
FROM
	CUSTOMER_BEHAVIOR_ANALYSIS
	fetch first 5 rows only;
--Top 5
select 
item_purchased,
ROUND(avg(review_rating)::NUMERIC, 2) as avg_rating 
from CUSTOMER_BEHAVIOR_ANALYSIS
group by item_purchased
order by avg_rating desc
fetch first 5 rows only;


--Bottom 5
select 
item_purchased,
ROUND(avg(review_rating)::NUMERIC, 2) as avg_rating 
from CUSTOMER_BEHAVIOR_ANALYSIS
group by item_purchased
order by avg_rating
fetch first 5 rows only;
--❓ Business Problem :- No visibility into product performance based on customer satisfaction.

--🚀 Impact :- 
				--Promotes high-performing products
				--Improves low-rated products
				--Enhances customer experience

-----------------------------------------------------------------------------------------------------------------------


-- 6. Average purchase: Standard vs Express shipping
SELECT * 
FROM
	CUSTOMER_BEHAVIOR_ANALYSIS
	fetch first 5 rows only;
select 
shipping_type,
ROUND(avg(purchase_amount)::NUMERIC, 2) as avg_purchase
from CUSTOMER_BEHAVIOR_ANALYSIS
group by shipping_type
having shipping_type in ('Express','Standard');

--❓ Business Problem :- Unclear if faster shipping leads to higher spending.


--🚀 Impact
			--Helps optimize shipping pricing strategy
			--Encourages premium shipping adoption
			--Increases average order value

------------------------------------------------------------------------------------

-- 7.Do subscribed customers spend more? Compare average speed and total revenue between subscribers and non-subscribers.
SELECT * 
FROM
	CUSTOMER_BEHAVIOR_ANALYSIS
	fetch first 5 rows only;
select 
subscription_status,
count(customer_id) as users,
ROUND(avg(purchase_amount)::NUMERIC, 2) as avg_spend,
ROUND(sum(purchase_amount)::NUMERIC, 2) as total_revenue
FROM
	CUSTOMER_BEHAVIOR_ANALYSIS
group by subscription_status
order by total_revenue desc;

--❓ Business Problem :- The effectiveness of subscription programs is unknown.

--🚀 Impact
			--Validates subscription model performance
			--Improves customer loyalty programs
			--Increases customer lifetime value (CLV)

-----------------------------------------------------------------------------------------------

-- 8. Top 5 products with highest discount usage %
SELECT * 
FROM
	CUSTOMER_BEHAVIOR_ANALYSIS
	fetch first 5 rows only;

select 
item_purchased,
count(item_purchased) as total_number_of_times_sold,
count(case when discount_applied = 'Yes' THEN 1 end ) as number_of_times_sold_when_discount,
count(case when discount_applied = 'Yes' THEN 1 end )*100.0/count(*) as discount_percentage
from CUSTOMER_BEHAVIOR_ANALYSIS
group by item_purchased
order by discount_percentage desc
fetch first 5 rows only;

-- ❓ Business Problem :- Some products may be overly dependent on discounts.

--🚀 Impact:- 
			--Identifies discount-driven products
			--Helps optimize pricing strategy
			--Reduces profit margin loss


------------------------------------------------------------------------------------------

-- 9. Segment customer into new, returning and loyal based on their total number of previous purchase, and show the count of each segment.
SELECT * FROM CUSTOMER_BEHAVIOR_ANALYSIS
fetch first 5 rows only;

SELECT 
	CASE 
		WHEN previous_purchases= '0' THEN 'New Customer'
		WHEN previous_purchases BETWEEN 1 AND 15  THEN 'Returning Customer'
	ELSE 'Loyal Customers'
END AS customer_segment,
COUNT(*) AS customer_count
FROM CUSTOMER_BEHAVIOR_ANALYSIS
GROUP BY CASE 
		WHEN previous_purchases= '0' THEN 'New Customer'
		WHEN previous_purchases BETWEEN 1 AND 15  THEN 'Returning Customer'
	ELSE 'Loyal Customers'
END;

--❓ Business Problem :- Lack of customer segmentation leads to generic strategies.


--🚀 Impact:- 
			--Enables personalized marketing
			--Improves retention strategies
			--Increases conversion rates
-----------------------------------------------------------------------------------------
--10. What are the top 3 most purchased products within each category ?

SELECT * FROM CUSTOMER_BEHAVIOR_ANALYSIS
fetch first 5 rows only;

WITH CTE AS 
(
SELECT 
	category,
	item_purchased,
	COUNT(item_purchased) AS most_purchased,
	RANK() OVER (PARTITION BY category ORDER BY COUNT(item_purchased) DESC) AS RNK
FROM CUSTOMER_BEHAVIOR_ANALYSIS
GROUP BY category,item_purchased
)
SELECT * FROM CTE
WHERE RNK <4;

--❓ Business Problem:- The company doesn’t know top-performing products within categories.


--🚀 Impact
			--Improves product placement & recommendations
			--Helps inventory optimization
			--Increases sales through best-sellers

------------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------------------
--11. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT * FROM CUSTOMER_BEHAVIOR_ANALYSIS
fetch first 5 rows only;

SELECT
	CASE 
		WHEN previous_purchases > 5 THEN 'Repeat Buyers'
		ELSE 'Normal Buyers'
	END AS customer_type,
	subscription_status,
	COUNT(*) AS customer_count,
	ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY CASE 
										WHEN previous_purchases > 5 THEN 'Repeat Buyers'
										ELSE 'Normal Buyers'
									END
									)  ::NUMERIC,2) AS percents
FROM CUSTOMER_BEHAVIOR_ANALYSIS
GROUP BY CASE 
		WHEN previous_purchases > 5 THEN 'Repeat Buyers'
		ELSE 'Normal Buyers'
	END,subscription_status;

--❓ Business Problem :- Unclear relationship between loyalty and subscription.

--🚀 Impact:- 
			--Improves subscription targeting
			--Increases conversion to paid programs
			--increase customer retention strategy

-------------------------------------------------------------------------------------------------

-- 12. What is the revenue contribution of each age group?
SELECT * FROM CUSTOMER_BEHAVIOR_ANALYSIS
fetch first 5 rows only;

SELECT 
	CASE 
		WHEN age BETWEEN 18 AND 25 THEN '18-25'
		WHEN Age BETWEEN 26 AND 35 THEN '26-35'
		WHEN Age BETWEEN 36 AND 50 THEN '35-50'
		ELSE '51+'
	END AS age_group,
	ROUND(SUM(purchase_amount)::NUMERIC, 2) AS total_revenue
FROM CUSTOMER_BEHAVIOR_ANALYSIS
GROUP BY CASE 
		WHEN age BETWEEN 18 AND 25 THEN '18-25'
		WHEN Age BETWEEN 26 AND 35 THEN '26-35'
		WHEN Age BETWEEN 36 AND 50 THEN '35-50'
		ELSE '51+'
	END
	ORDER BY total_revenue DESC;

--❓ Business Problem:- No visibility into which age group contributes most to revenue.

--🚀 Impact:-
			--Enables age-based targeting
			--Enhances marketing efficiency